[build-system]
requires = [
    "setuptools>=65",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "probjax"
description = "Jax library for probabilistic computations"
version = "0.1.1"
requires-python = ">=3.11"
authors = [
    { name = "Manuel Gloeckler", email = "manuel.gloeckler@uni-tuebingen.de" }
]
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
keywords = ["probabilistic", "jax", "computation"]
dependencies = [
    "numpy >= 2.0.0",
    "jax >= 0.9.0, < 0.10",
    "einops",
    "optax",
    "flax >= 0.12.6",
    "jaxtyping",
    "networkx",
    "blackjax == 1.6.2",
]

[project.optional-dependencies]
wasserstein = [
    "ott-jax",
]
plot = [
    "matplotlib",
]
notebooks = [
    "matplotlib",
    "jupyter",
    "ipykernel",
    "ipywidgets",
]
benchmark = [
    "psutil",
    "pynvml",
]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-benchmark",
    "ruff",
    "pytest-xdist",
    "scipy",
]
cuda13 = [
    "jax[cuda13]>=0.9.0,<0.10",
]
metal = [
    "jax-metal",
]


[tool.setuptools.packages.find]
where = ["."]
include = ["probjax*"]

[project.urls]
Homepage = "https://github.com/mackelab/probjax"
Repository = "https://github.com/mackelab/probjax"
Issues = "https://github.com/mackelab/probjax/issues"

[tool.ruff]
line-length = 88
exclude = ["*.ipynb"]

[tool.ruff.lint]
select = ["E", "F", "W", "B", "SIM", "I"]
ignore = [
    "E731",  # allow naming lambda functions.
    "B008"  # allow function calls in default args.
]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]  # allow unused imports and undefined names
"test_*.py" = ["F403", "F405"]

[tool.ruff.lint.isort]
case-sensitive = true
lines-between-types = 0  # like isort default.
relative-imports-order = "furthest-to-closest"  # like isort default.
known-first-party = ["sbi", "tests", "tutorials"]

[tool.ruff.format]
exclude = ["*.ipynb"]
preview = true
quote-style = "preserve"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.pycodestyle]
max-line-length = 88
ignore = ["E203", "W503"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--benchmark-sort=name"
filterwarnings = [
    "ignore:Setting `jax_pmap_shmap_merge` is deprecated in JAX v0.9.0 and will be removed in JAX v0.10.0.:DeprecationWarning:jax._src.config",
]
