# Import all from flax.nnx
from flax.nnx.nn import *  # type: ignore

from probjax.nn.io_util import DataLoader, chunkify

# Override specific imports with probjax implementations
from probjax.nn.layers import (
    AdditiveBinaryFuse,
    AdditiveFuse,
    Affine,
    AffineFuse,
    BinaryFuse,
    ConcatFuse,
    ContextFuse,
    ConvBlock,
    DropPath,
    Flip,
    GatedFuse,
    GaussianFourierEmbedding,
    LRUCell,
    LearnablePosEncode,
    MambaCell,
    MaskedLinear,
    MultiHeadAttention,
    OneHot,
    Permute,
    PosEncode,
    RecurrentCell,
    RescaleConv,
    ResizeConv,
    ResnetBlock,
    RotaryPosEncode,
    Rotate,
    SSDCell,
    SpatialSelfAttention,
)
from probjax.nn.loss_fn import (
    build_denoising_loss,
    build_denoising_score_matching_loss,
    build_flow_matching_loss,
    build_score_matching_loss,
    build_sliced_score_matching_loss,
    build_target_score_matching_loss,
    build_time_dependent_denoising_loss,
    build_time_dependent_denoising_score_matching_loss,
    build_time_dependent_score_matching_loss,
    build_time_dependent_sliced_score_matching_loss,
    build_time_dependent_target_score_matching_loss,
)
from probjax.nn.nets import (
    EDM,
    MLP,
    VE,
    VP,
    AdditiveAutoregressiveFlow,
    AdditiveCouplingFlow,
    AffineAutoregressiveFlow,
    AffineCouplingFlow,
    AutoregressiveMLP,
    AutoregressiveTransformer,
    CouplingMLP,
    DeepSet,
    DiffusionDenoiser,
    FlowMatcher,
    LRUModel,
    LinearFlow,
    LinearMeanFlow,
    MaskedMLP,
    MeanFlowMatcher,
    NormalizingFlow,
    ResNet,
    Sequential,
    SplineAutoregressiveFlow,
    SplineCouplingFlow,
    Transformer,
    UNet,
)
from probjax.nn.pallas_kernels.attention import BlockSizes
from probjax.nn.pallas_kernels.attention_mask_bias import (
    AttentionBias,
    AttentionMask,
    CausalAlibiBias,
    CausalMask,
    ComposeMask,
    ConstantBias,
    DenseBias,
    DistanceDecayBias,
    IdentityBias,
    KeyPaddingMask,
    LocalWindowMask,
    MarginalizationMask,
    NoMask,
    NotMask,
    QKVLengthMask,
    SameSegmentMask,
    SeqLenMask,
    SymmetricAlibiBias,
    SumBias,
)
