

name: score_transformer 
backend: jax
device: gpu
params_train:
  max_num_epochs: 10000
  total_number_steps_scaling: 10.
  training_batch_size: 5000
  learning_rate: 5e-4
  clip_max_norm: 10.
  condition_mask_fn: structured
  condition_mask_fn_kwargs:
    p_joint: 0.2
    p_posterior: 0.2
    p_likelihood: 0.2
    p_rnd1: 0.2
    p_rnd2: 0.2
sde_params: # TODO: Make this a config subgroup
  name: 'vpsde'
  beta_max: 10.
  beta_min: 0.01
  T_max: 1.
  T_min: 1e-5
model_params:
  use_output_scale_fn: True



