
name: score_transformer_posterior
backend: jax
device: gpu


defaults:
  - model: score_transformer
  - train: train_score_transformer
  - sde: vpsde
  - posterior: backward_sde
  - override train/condition_mask_fn: posterior

