







name: score_transformer_graph
backend: jax
device: gpu
params_train:
  max_number_steps: 100000
  min_number_steps: 5000
  total_number_steps_scaling: 2
  training_batch_size: 5000
  learning_rate: 1e-3
  clip_max_norm: 10.
  validation_fraction: 0.05
  val_repeat: 5
  val_every: 1000
  condition_mask_fn: structured
  edge_mask_fn: faithfull
  condition_mask_fn_kwargs:
    p_joint: 0.2
    p_posterior: 0.2
    p_likelihood: 0.2
    p_rnd1: 0.2
    p_rnd2: 0.2
sde_params: # TODO: Make this a config subgroup
  name: 'vpsde'
  beta_max: 10.
  beta_min: 0.01
  T_max: 1.
  T_min: 1e-5
model_params:
  use_output_scale_fn: True



