name: benchmark_score_sbi
seed: 0

save_model: true
save_summary: true

defaults:
  - _self_
  - method: npe
  - task: two_moons
  - eval: c2st
  - launcher: slurm
  - sweeper: none
  - override hydra/launcher: submitit_slurm