token_dim: 30
condition_token_dim: 0
condition_token_init_scale: 0.1
condition_token_init_mean: 0.
condition_mode: 'none'
time_embedding_dim: 128
num_heads: 4
num_layers: 5
attn_size: 5
widening_factor: 2
num_hidden_layers: 2
skip_connection_attn: True
skip_connection_mlp: True
layer_norm: True