"""Convert curated example notebooks to Markdown for Zensical.

Zensical does not run MkDocs plugins, so ``mkdocs-jupyter`` cannot render
``.ipynb`` files directly (see zensical/zensical#52). Instead this script
pre-converts notebooks with the standard ``nbconvert`` Markdown exporter
before ``zensical build`` runs. Zensical then renders the generated Markdown
natively, with full theme, navigation, search and TOC integration.

Usage:
    python scripts/convert_notebooks.py
    python scripts/convert_notebooks.py --check   # CI: fail if output is stale
    zensical build --strict                       # afterwards

Policy: no re-execution. Committed cell outputs are reused as-is, which keeps
the docs build fast and deterministic (no JAX workload in CI). To refresh
outputs, re-run the notebook locally and commit the updated ``.ipynb``.
"""

from __future__ import annotations

import argparse
import difflib
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Curated subset rendered into the docs. Inclusion criteria: the notebook
# re-executes cleanly against current main (CI executes every tutorial page's
# code blocks via test_docs.py) and needs no sibling-helper imports. Expand
# deliberately -- heavy or stale notebooks stay out until modernized.
CURATED_NOTEBOOKS = [
    "examples/core/ppl.ipynb",
    "examples/inference/kalman_filter.ipynb",
    "examples/inference/smc.ipynb",
]

OUTPUT_DIR = REPO_ROOT / "docs" / "tutorials"

CURATED_STEMS = {Path(p).stem for p in CURATED_NOTEBOOKS}

# Matches Markdown links/images: [text](target) — group 1 is "!" or "".
LINK_RE = re.compile(r"(!?)\[([^\]]*)\]\(([^)]+)\)")


def _converter():
    try:
        import nbformat
        from nbconvert import MarkdownExporter
    except ImportError:
        print(
            "error: nbconvert/nbformat not installed. "
            "Install docs requirements: pip install -r docs/requirements.txt",
            file=sys.stderr,
        )
        raise SystemExit(2) from None
    return nbformat, MarkdownExporter


def convert_notebook(src: Path, dest: Path) -> tuple[str, dict[str, bytes]]:
    """Return (markdown_body, output_files) without executing the notebook."""
    nbformat, MarkdownExporter = _converter()
    notebook = nbformat.read(src, as_version=4)
    exporter = MarkdownExporter()
    # Direct image links at "<stem>_files/..." so they resolve next to the
    # generated Markdown page.
    files_dir = dest.stem + "_files"
    body, resources = exporter.from_notebook_node(
        notebook,
        resources={"metadata": {"name": dest.stem}, "output_files_dir": files_dir},
    )
    return body, resources.get("outputs", {})


def header_for(src_relative: str) -> str:
    return (
        "<!-- AUTOGENERATED by scripts/convert_notebooks.py — DO NOT EDIT.\n"
        f"     Source: {src_relative}. Outputs are committed in the notebook;\n"
        "     this conversion does not re-execute code. -->\n\n"
        f"> **Tutorial notebook.** Source "
        f"[`.ipynb on GitHub`](https://github.com/mackelab/probjax/blob/main/{src_relative}).\n\n"
    )


def rewrite_links(body: str, src_relative: str) -> str:
    """Relocate notebook-relative links to the generated page location.

    Notebooks link relative to ``examples/<area>/`` (e.g.
    ``../../docs/guides/smc.md`` or a sibling ``temporal_smc.ipynb``), but the
    generated page lives at ``docs/tutorials/``. Without rewriting, ``zensical
    build --strict`` fails on links that resolve outside the docs tree.
    """

    def repl(match: re.Match[str]) -> str:
        bang, text, target = match.groups()
        if target.startswith(("http://", "https://", "//", "mailto:", "#")):
            return match.group(0)
        # Repo-relative docs links from inside examples/: ../../docs/X -> ../X
        docs_prefix = "../../docs/"
        if target.startswith(docs_prefix):
            return f"{bang}[{text}](../{target[len(docs_prefix) :]})"
        # Sibling notebook links: curated ones become local pages, the rest
        # point at the source on GitHub (always resolvable, strict-safe).
        if target.endswith(".ipynb"):
            stem = Path(target).stem
            if stem in CURATED_STEMS:
                return f"{bang}[{text}](./{stem}.md)"
            sibling = str(Path(src_relative).parent / target)
            url = f"https://github.com/mackelab/probjax/blob/main/{sibling}"
            return f"{bang}[{text}]({url})"
        return match.group(0)

    return LINK_RE.sub(repl, body)


def render(src_relative: str) -> tuple[Path, str, dict[str, bytes]]:
    src = REPO_ROOT / src_relative
    if not src.exists():
        raise SystemExit(f"error: missing notebook: {src_relative}")
    dest = OUTPUT_DIR / (src.stem + ".md")
    body, outputs = convert_notebook(src, dest)
    body = rewrite_links(body, src_relative)
    return dest, header_for(src_relative) + body, outputs


def write_outputs(dest: Path, files: dict[str, bytes]) -> None:
    files_dir = dest.parent / (dest.stem + "_files")
    if files_dir.exists():
        shutil.rmtree(files_dir)
    if not files:
        return
    for name, data in files.items():
        # Keys already carry the "<stem>_files/..." prefix; resolve them
        # relative to the tutorials dir so nbconvert stays the authority.
        target = dest.parent / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated Markdown differs from committed conversion.",
    )
    args = parser.parse_args()

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    failures: list[str] = []

    for src_relative in CURATED_NOTEBOOKS:
        dest, content, files = render(src_relative)
        if args.check:
            existing = dest.read_text(encoding="utf-8") if dest.exists() else None
            if existing != content:
                failures.append(src_relative)
                diff = difflib.unified_diff(
                    (existing or "").splitlines(),
                    content.splitlines(),
                    fromfile=str(dest),
                    tofile="generated",
                    lineterm="",
                )
                print(f"stale: {src_relative} -> {dest.relative_to(REPO_ROOT)}")
                print("\n".join(list(diff)[:20]))
            continue
        dest.write_text(content, encoding="utf-8")
        write_outputs(dest, files)
        print(f" - {src_relative} -> {dest.relative_to(REPO_ROOT)}")

    if failures:
        print(
            "\nerror: generated tutorials are stale. "
            "Run 'python scripts/convert_notebooks.py' and commit the result.",
            file=sys.stderr,
        )
        raise SystemExit(1)


if __name__ == "__main__":
    main()
